name: getx_pattern_starter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.4
  image_picker: 0.8.6
  sp_util: 2.0.3
  material_design_icons_flutter: 6.0.7096
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3
  google_fonts: 5.1.0
  firebase_core: 2.15.1
  cloud_firestore: 4.9.1
  firebase_auth: 4.9.0
  firebase_storage: 11.2.6
  uuid: ^3.0.5
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.1.5
  video_player: ^2.7.1
  appinio_video_player: ^1.2.2
  vertical_card_pager: ^1.5.0
  flutter_cached_pdfview: ^0.4.2
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^23.1.36
  chewie: 1.7.1
  photo_view: ^0.14.0
  audioplayers: ^5.1.0
  flutter_dotenv: 5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/backsound/
  uses-material-design: true
